// Canonical hiring catalog — every role EduRankAI advertises, self-hosted.
// Imported into the roles table via /admin/roles ("Import role catalog"):
// departments are upserted, roles are inserted ONLY if the slug is missing,
// so re-importing never overwrites edits made in the admin panel.
//
// This exists to end per-day sponsored-listing bills on external job boards:
// the careers portal + JobPosting structured data (free Google indexing) is
// the primary channel; external boards become optional.

export interface CatalogDepartment {
  id: string;
  name: string;
  icon: string;
  description: string;
}

export interface CatalogRole {
  slug: string;
  departmentId: string;
  title: string;
  level: 'C-Level' | 'Lead' | 'Senior' | 'Mid' | 'Junior' | 'Intern' | 'Apprentice';
  function: string;
  engagementType: 'Full-Time' | 'Internship' | 'Apprenticeship';
  location: string;
  duration: string;
  salary: string;
  about: string;
  responsibilities: string[];
  skills: string[];
  eligibility: string[];
  isFeatured?: boolean;
  openings?: number;
  /** Substring matched against product slugs at import time (e.g. 'karate'). */
  productMatch?: string;
}

export const CATALOG_DEPARTMENTS: CatalogDepartment[] = [
  { id: 'engineering', name: 'Engineering', icon: 'code', description: 'Platform, applications, infrastructure, security, and quality engineering across the EduRankAI ecosystem.' },
  { id: 'ai-research', name: 'AI & Research', icon: 'brain', description: 'Applied AI, computer vision, knowledge systems, MLOps, and frontier research.' },
  { id: 'xr-emerging', name: 'Extended Reality & Emerging Tech', icon: 'cube', description: 'Spatial computing, AR/VR/MR, holographic systems, digital twins, and human-computer interaction.' },
  { id: 'design', name: 'Design', icon: 'pen', description: 'Product design, UI/UX, motion, and visual storytelling.' },
  { id: 'product-programs', name: 'Product & Programs', icon: 'layers', description: 'Program management, product operations, and cross-company execution.' },
  { id: 'growth', name: 'Growth & Partnerships', icon: 'trending-up', description: 'Business development, marketing, community, developer relations, and sales.' },
  { id: 'people', name: 'People & Talent', icon: 'users', description: 'Talent acquisition and people operations.' },
  { id: 'finance-legal', name: 'Finance, Legal & Compliance', icon: 'scale', description: 'Finance, corporate compliance, legal, and intellectual property.' },
  { id: 'operations', name: 'Operations & Support', icon: 'briefcase', description: 'Customer success, product support, documentation, and knowledge management.' },
  { id: 'martial-arts', name: 'Martial Arts & Sports', icon: 'activity', description: 'The global karate and martial-arts platform: instruction, community, and development.' },
  { id: 'innovation-grants', name: 'Innovation & Grants', icon: 'lightbulb', description: 'Non-dilutive funding: government grants, innovation schemes, and R&D incentives that keep EduRankAI independent.' },
];

const REMOTE_IN = 'Remote / Hybrid (India)';
const PERM = 'Permanent';

export const ROLE_CATALOG: CatalogRole[] = [
  // ─── AI & RESEARCH ────────────────────────────────────────────────
  {
    slug: 'senior-ai-engineer-computer-vision',
    departmentId: 'ai-research',
    title: 'Senior AI Engineer (Computer Vision & Intelligent Systems)',
    level: 'Senior',
    function: 'Build production computer-vision systems — detection, pose, video analytics, 3D vision — that run in real time.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 20,00,000 - 40,00,000 per annum',
    isFeatured: true,
    about: 'Much of the most valuable AI work is visual: proctoring integrity, sports analytics, document understanding, industrial inspection, immersive learning. We are hiring a senior engineer who has shipped production computer-vision systems — not notebooks — and who is comfortable owning the full path from camera to decision. Strong engineers in this specialisation often skip listings that only say "LLM Engineer"; this role exists so they do not have to.',
    responsibilities: [
      'Design and ship real-time computer-vision pipelines: object detection, tracking, pose estimation, OCR, and video analytics.',
      'Own model selection, training, optimisation, and deployment (quantisation, GPU inference, edge targets).',
      'Build multi-camera and 3D-vision systems: calibration, reconstruction, trajectory estimation, sensor fusion.',
      'Integrate vision systems with our proctoring, assessment, and sports platforms with strict latency budgets.',
      'Establish evaluation harnesses: dataset curation, ground truth, drift monitoring, and failure analysis.',
      'Mentor mid-level engineers and set the technical bar for applied vision work.',
    ],
    skills: ['Python', 'C++', 'PyTorch', 'OpenCV', 'TensorRT or equivalent inference optimisation', 'Object detection (YOLO-family, transformer detectors)', 'Pose estimation', 'Multi-camera calibration & 3D reconstruction', 'Real-time systems', 'Docker & Kubernetes', 'Linux', 'GPU programming (CUDA a plus)'],
    eligibility: [
      "Bachelor's or Master's in Computer Science, Electrical Engineering, or related field.",
      '4-10+ years building production computer-vision or real-time ML systems.',
      'At least one system you built processing live video in production.',
      'Strong software-engineering fundamentals: testing, profiling, deployment.',
    ],
  },
  {
    slug: 'senior-ai-infrastructure-mlops-engineer',
    departmentId: 'ai-research',
    title: 'Senior AI Infrastructure & MLOps Engineer',
    level: 'Senior',
    function: 'Own the training-to-production path: pipelines, serving, monitoring, cost control.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 20,00,000 - 38,00,000 per annum',
    about: 'Models are only useful when they ship and stay healthy. You will own the infrastructure that takes models from experiment to production across our ecosystem — training pipelines, model serving, observability, and hard cost discipline on limited compute.',
    responsibilities: [
      'Design and operate ML pipelines: data ingestion, training, evaluation, registry, rollout.',
      'Build low-latency, autoscaling model-serving infrastructure with graceful degradation.',
      'Instrument model and data drift monitoring, alerting, and rollback paths.',
      'Drive GPU/compute cost efficiency: batching, caching, quantisation, spot capacity.',
      'Harden the platform: reproducible environments, CI/CD for models, access control.',
      'Partner with applied AI engineers to productionise research prototypes.',
    ],
    skills: ['Python', 'Docker', 'Kubernetes', 'CI/CD', 'Model serving (Triton/TorchServe or equivalent)', 'Workflow orchestration', 'Observability (metrics, tracing, logging)', 'Linux', 'Infrastructure as code', 'Cloud cost optimisation'],
    eligibility: [
      "Bachelor's or Master's in Computer Science or related field.",
      '4-10 years in infrastructure, platform, or ML engineering.',
      'Production ML deployment experience at scale.',
    ],
  },
  {
    slug: 'senior-knowledge-graph-semantic-ai-engineer',
    departmentId: 'ai-research',
    title: 'Senior Knowledge Graph & Semantic AI Engineer',
    level: 'Senior',
    function: 'Build the knowledge layer: graphs, ontologies, retrieval, and reasoning over structured knowledge.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 20,00,000 - 38,00,000 per annum',
    about: 'Our education, assessment, and research products need machine-usable knowledge — curricula, skills, institutions, evidence — not just text. You will design the knowledge graphs and semantic infrastructure that make our AI systems grounded, auditable, and genuinely useful.',
    responsibilities: [
      'Design ontologies and knowledge graphs for courses, skills, credentials, and institutional data.',
      'Build entity resolution, linking, and knowledge-extraction pipelines from messy real-world sources.',
      'Implement graph-powered retrieval and reasoning for AI tutoring and search.',
      'Own graph storage, query performance, and data quality at scale.',
      'Publish internal standards for knowledge modelling across product teams.',
    ],
    skills: ['Knowledge graphs (RDF/property graphs)', 'Graph databases', 'SPARQL/Cypher', 'Entity resolution', 'Information extraction', 'Python', 'Embeddings & vector retrieval', 'Ontology design', 'Data pipelines'],
    eligibility: [
      "Bachelor's or Master's in Computer Science, Computational Linguistics, or related field.",
      '4-10 years in knowledge engineering, semantic systems, or data-intensive backends.',
      'Shipped at least one production system built on a knowledge graph or large-scale structured knowledge.',
    ],
  },
  {
    slug: 'senior-ai-engineer-llms-agentic-systems',
    departmentId: 'ai-research',
    title: 'Senior AI Engineer (LLMs & Agentic Systems)',
    level: 'Senior',
    function: 'Build grounded, evaluated LLM features: tutoring, assessment, agents with guardrails.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 20,00,000 - 40,00,000 per annum',
    about: 'We ship LLM-powered tutoring, assessment, and workflow features to real learners — which means grounding, evaluation, and cost control matter more than demos. You will own LLM features end to end: retrieval design, tool use, guardrails, and the evaluation harnesses that prove they work.',
    responsibilities: [
      'Design and ship retrieval-grounded LLM features for tutoring, assessment, and internal tools.',
      'Build agentic workflows with tool use, structured outputs, and hard safety guardrails.',
      'Own evaluation: golden sets, regression suites, human-in-the-loop review, hallucination tracking.',
      'Optimise for cost and latency: caching, routing, context management, batching.',
      'Set the internal playbook for responsible LLM deployment in education.',
    ],
    skills: ['Python', 'LLM APIs & fine-tuning', 'Retrieval-augmented generation', 'Vector databases & embeddings', 'Prompt & context engineering', 'Evaluation design', 'TypeScript (a plus)', 'Cost/latency optimisation'],
    eligibility: [
      "Bachelor's or Master's in Computer Science or related field.",
      '4-10 years of software engineering with 2+ years shipping LLM-backed features to production.',
      'Evidence of rigorous evaluation practice, not just integrations.',
    ],
  },
  {
    slug: 'senior-data-scientist-decision-intelligence',
    departmentId: 'ai-research',
    title: 'Senior Data Scientist (Decision Intelligence & Knowledge Systems)',
    level: 'Senior',
    function: 'Turn learning, assessment, and operations data into decisions the company actually makes.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 18,00,000 - 35,00,000 per annum',
    about: 'Every product in our ecosystem generates evidence — about learning, integrity, engagement, and operations. You will build the statistical models, experiments, and decision frameworks that convert that evidence into product and business decisions, with the scepticism of a scientist and the pragmatism of an operator.',
    responsibilities: [
      'Design and analyse experiments across learning products; guard against p-hacking and vanity metrics.',
      'Build predictive and causal models for learner outcomes, retention, and assessment integrity.',
      'Define and maintain company metrics with clear ownership and honest caveats.',
      'Partner with engineering on data pipelines, feature stores, and analytics tooling.',
      'Communicate findings so leaders can act on them — including when the answer is "we do not know yet".',
    ],
    skills: ['Statistics & causal inference', 'Python (pandas, scikit-learn)', 'SQL', 'Experiment design', 'ML modelling', 'Data visualisation', 'Communication of uncertainty'],
    eligibility: [
      "Master's or PhD in a quantitative field, or equivalent demonstrated practice.",
      '4-10 years in data science with shipped, decision-changing work.',
    ],
  },
  {
    slug: 'chief-solutions-architect-ai-quantum-emerging',
    departmentId: 'ai-research',
    title: 'Chief Solutions Architect (Artificial Intelligence, Quantum Computing & Emerging Technologies)',
    level: 'Lead',
    function: 'Own the technical architecture across the ecosystem and the bridge to frontier programmes.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 40,00,000 - 75,00,000 per annum',
    isFeatured: true,
    about: 'EduRankAI runs many ventures on one thesis. The Chief Solutions Architect keeps that technically honest: one coherent architecture across education, assessment, consumer ventures, and frontier research (including our quantum-era and aerospace programmes), with pragmatic choices about what is real today versus what is research.',
    responsibilities: [
      'Own end-to-end solution architecture across products: boundaries, contracts, data flows, security posture.',
      'Translate frontier programmes (quantum-resilient systems, autonomous swarms, advanced AI) into staged, buildable roadmaps.',
      'Run architecture reviews; kill complexity that does not pay rent.',
      'Lead technical due diligence for partnerships and government engagements.',
      'Mentor senior engineers into architects.',
    ],
    skills: ['Distributed systems architecture', 'Cloud & edge infrastructure', 'AI/ML system design', 'Security architecture', 'Post-quantum cryptography awareness', 'Technical writing', 'Stakeholder leadership'],
    eligibility: [
      '10+ years in software engineering with 4+ years in architecture leadership.',
      'Track record of architectures that survived scale and organisational change.',
      'Comfort operating across research and production concerns.',
    ],
  },

  // ─── XR & EMERGING TECH ───────────────────────────────────────────
  {
    slug: 'senior-xr-engineer-spatial-computing',
    departmentId: 'xr-emerging',
    title: 'Senior XR Engineer (Spatial Computing, AR/VR/MR & Holographic Technologies)',
    level: 'Senior',
    function: 'Engineer the next dimension of human-computer interaction: immersive, intelligent, interactive environments.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 20,00,000 - 40,00,000 per annum',
    isFeatured: true,
    about: 'The future of computing extends beyond traditional screens into immersive, intelligent, and interactive environments. We are exploring the convergence of Extended Reality, Spatial Computing, Artificial Intelligence, Digital Twins, Holographic Technologies, Computer Vision, High-Performance Computing, and Human-Centered Design to create next-generation educational, research, industrial, and enterprise experiences. Your mission: build immersive, intelligent, and scalable XR solutions that bridge the physical and digital worlds while contributing to our long-term vision for advanced computing and interactive technologies.',
    responsibilities: [
      'Design and develop immersive AR, VR, MR, and XR applications for education, research, healthcare, enterprise, and industrial use cases.',
      'Build interactive spatial-computing experiences: gesture, voice, eye-tracking, and natural interaction systems, optimised for usability, accessibility, and comfort.',
      'Develop advanced 3D visualisation and holographic experiences, immersive educational simulations, and digital laboratories with real-time rendering.',
      'Build Digital Twin applications and virtual laboratories that integrate real-world data with virtual environments.',
      'Contribute across the emerging-technology portfolio: computer vision, AI integration, IoT and robotics integration, human-computer interaction.',
      'Set engineering standards for performance (frame budgets), comfort, and cross-platform delivery.',
    ],
    skills: ['Unity', 'Unreal Engine', 'C#', 'C++', 'OpenXR', 'Mobile AR frameworks', 'OpenCV / computer vision', '3D graphics & spatial mapping', 'Digital twins', 'Holographic displays', 'AI integration', 'GPU programming', 'Blender or equivalent 3D tooling'],
    eligibility: [
      "Bachelor's or Master's in Computer Science, Computer Graphics, XR, Game Development, Engineering, HCI, or a related discipline.",
      '4-10+ years in XR, AR/VR, 3D graphics, simulation, or immersive technologies.',
      'Strong understanding of spatial computing and interactive systems.',
      'Excellent software-engineering and problem-solving skills.',
      'Exceptional candidates with significant contributions to immersive technologies may be considered beyond the advertised range.',
    ],
  },

  // ─── ENGINEERING ──────────────────────────────────────────────────
  {
    slug: 'senior-full-stack-engineer-platform',
    departmentId: 'engineering',
    title: 'Senior Full Stack Engineer (Platform & Intelligent Systems)',
    level: 'Senior',
    function: 'Own product surfaces end to end across the ecosystem: web, APIs, data, performance.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 18,00,000 - 35,00,000 per annum',
    about: 'Our ecosystem ships many products on one platform: a virtual university, assessments with anti-cheat instrumentation, an admissions portal, consumer ventures. You will own features across the stack — from schema to interaction — with a bias for accessible, fast, honest software.',
    responsibilities: [
      'Ship full-stack features: data model, API, UI, instrumentation, rollout.',
      'Keep surfaces fast (Core Web Vitals) and accessible (WCAG 2.1 AA) by default.',
      'Design pragmatic APIs and schemas that survive product iteration.',
      'Harden reliability: error budgets, graceful degradation, observability.',
      'Review code and mentor mid-level engineers.',
    ],
    skills: ['TypeScript', 'Node.js', 'Modern SSR frameworks', 'PostgreSQL', 'API design', 'Caching & performance', 'Testing', 'Accessibility (WCAG)', 'CI/CD'],
    eligibility: [
      "Bachelor's in Computer Science or equivalent practice.",
      '4-10 years shipping production web applications.',
      'Evidence of end-to-end ownership, not just tickets.',
    ],
  },
  {
    slug: 'senior-applications-engineer-multi-platform',
    departmentId: 'engineering',
    title: 'Senior Applications Engineer (Multi-Platform & Intelligent Computing)',
    level: 'Senior',
    function: 'Build robust applications across web, desktop, and mobile targets with production discipline.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 18,00,000 - 35,00,000 per annum',
    about: 'We build software that must work offline, on low-end phones, and under real-world networks — for learners, examiners, and consumers. You will engineer applications across platforms with the fundamentals that make them dependable: strong typing, testing, profiling, and deployment discipline.',
    responsibilities: [
      'Build and maintain multi-platform applications (web, PWA, desktop, mobile wrappers).',
      'Engineer offline-first flows, sync, and conflict handling.',
      'Integrate intelligent features (vision, speech, LLM-backed) behind stable interfaces.',
      'Own performance on constrained devices and networks.',
      'Contribute to shared libraries, tooling, and engineering standards.',
    ],
    skills: ['TypeScript/JavaScript', 'C++ or Java or C# (at least one)', 'Python', 'PostgreSQL', 'Docker', 'Kubernetes', 'Linux', 'Distributed systems basics', 'Offline-first patterns'],
    eligibility: [
      "Bachelor's or Master's in Computer Science or related field.",
      '4-10 years in application engineering with production deployments.',
    ],
  },
  {
    slug: 'senior-devops-cloud-infrastructure-engineer',
    departmentId: 'engineering',
    title: 'Senior DevOps & Cloud Infrastructure Engineer',
    level: 'Senior',
    function: 'Own build, deploy, run: infrastructure as code, observability, cost, and incident discipline.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 18,00,000 - 35,00,000 per annum',
    about: 'Many products, small team, limited budget: our infrastructure must be boring, observable, and cheap. You will own the pipelines and platforms that let engineers ship safely every day — and the cost discipline that keeps an independent company independent.',
    responsibilities: [
      'Own CI/CD pipelines, environments, and release engineering.',
      'Run infrastructure as code; kill snowflakes.',
      'Build observability: metrics, logs, traces, alerting with low noise.',
      'Drive cloud cost optimisation and capacity planning.',
      'Lead incident response and post-incident learning.',
      'Harden security: secrets, least privilege, supply-chain hygiene.',
    ],
    skills: ['Linux', 'Docker', 'Kubernetes', 'Infrastructure as code (Terraform or equivalent)', 'CI/CD', 'Cloud platforms', 'Networking', 'Observability stacks', 'Shell & Python scripting', 'Security fundamentals'],
    eligibility: [
      "Bachelor's in Computer Science or equivalent practice.",
      '4-10 years in DevOps/SRE/platform roles.',
      'You have been on call for systems you built.',
    ],
  },
  {
    slug: 'senior-cybersecurity-engineer',
    departmentId: 'engineering',
    title: 'Senior Cybersecurity Engineer (Offensive Security & Security Architecture)',
    level: 'Senior',
    function: 'Attack our systems before anyone else does; architect so attacks fail anyway.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 20,00,000 - 38,00,000 per annum',
    about: 'We hold exam integrity data, identity verifications, payments, and minors\' learning records. That obliges us to a higher bar. You will run offensive security against our own estate (authorised, scoped, documented) and turn findings into architecture: the goal is not clever exploits, it is systems where exploits do not matter.',
    responsibilities: [
      'Run authorised penetration tests and red-team exercises against our own products and infrastructure.',
      'Own security architecture reviews for new features: authN/Z, session, crypto, data flows.',
      'Build secure-by-default patterns and paved roads for engineers.',
      'Operate vulnerability management: triage, remediation SLAs, verification.',
      'Lead incident response for security events; run post-mortems without blame.',
      'Maintain our responsible-disclosure programme.',
    ],
    skills: ['Web & API security (OWASP)', 'Penetration testing', 'Security architecture', 'Applied cryptography', 'Cloud security', 'Identity & access management', 'Scripting (Python)', 'Threat modelling', 'Incident response'],
    eligibility: [
      "Bachelor's in Computer Science or equivalent; certifications (OSCP or similar) respected but not required.",
      '4-10 years in security engineering with hands-on offensive work.',
      'Strict professional ethics: authorised targets only, always documented.',
    ],
  },
  {
    slug: 'senior-qa-automation-engineer',
    departmentId: 'engineering',
    title: 'Senior Quality Assurance & Automation Engineer',
    level: 'Senior',
    function: 'Make quality systematic: automation, regression safety, and release confidence.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 14,00,000 - 28,00,000 per annum',
    about: 'Learners take exams on our platform; examiners trust our results; consumers pay through our flows. A regression is not an inconvenience — it is broken trust. You will build the automation and quality systems that let a fast-shipping team ship without fear.',
    responsibilities: [
      'Design and own end-to-end, integration, and API test automation.',
      'Build CI quality gates that are fast enough that nobody wants to skip them.',
      'Test the hard parts: payments, proctoring, offline sync, accessibility.',
      'Establish exploratory-testing practice and risk-based test planning.',
      'Track quality metrics honestly: escape rate, flake rate, time-to-detect.',
    ],
    skills: ['Test automation (Playwright/Cypress or equivalent)', 'API testing', 'TypeScript/JavaScript', 'CI/CD integration', 'Performance testing', 'Accessibility testing', 'SQL', 'Test strategy'],
    eligibility: [
      "Bachelor's degree or equivalent practice.",
      '4-8 years in QA/SDET roles with automation ownership.',
    ],
  },

  // ─── DESIGN ───────────────────────────────────────────────────────
  {
    slug: 'ui-ux-designer',
    departmentId: 'design',
    title: 'UI/UX Designer',
    level: 'Mid',
    function: 'Design honest, accessible, fast interfaces across the ecosystem.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 8,00,000 - 18,00,000 per annum',
    about: 'Our products serve learners on cheap phones, examiners under pressure, and consumers who deserve interfaces without dark patterns. You will design flows and screens that are beautiful because they are clear — and measurably usable, not just pretty in a portfolio.',
    responsibilities: [
      'Design end-to-end flows: research, wireframes, high-fidelity UI, hand-off.',
      'Maintain and extend the design system; keep accessibility (WCAG 2.1 AA) non-negotiable.',
      'Prototype and test with real users; let evidence beat opinion.',
      'Partner daily with engineers so shipped equals designed.',
      'Design responsibly: no dark patterns, no fake urgency, no manipulative defaults.',
    ],
    skills: ['Product design', 'Figma or equivalent', 'Design systems', 'Interaction design', 'Accessibility', 'Prototyping', 'Basic HTML/CSS literacy', 'User research'],
    eligibility: [
      '2-6 years designing shipped digital products.',
      'A portfolio showing process, not just final screens.',
    ],
  },
  {
    slug: 'senior-product-designer-ai-systems',
    departmentId: 'design',
    title: 'Senior Product Designer (AI & Intelligent Systems)',
    level: 'Senior',
    function: 'Design AI-powered experiences that are trustworthy, legible, and humane.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 15,00,000 - 30,00,000 per annum',
    about: 'AI features fail in design more often than in models: unclear confidence, no recourse, invisible failure states. You will lead design for our AI-powered surfaces — tutoring, assessment, integrity review — where trust, explainability, and human override are product requirements, not afterthoughts.',
    responsibilities: [
      'Lead design for AI-first features: tutoring, feedback, review queues, advisory flags.',
      'Design states of uncertainty honestly: confidence, provenance, and appeal paths.',
      'Define patterns for human-in-the-loop review (nothing auto-penalises a person).',
      'Raise the craft bar: motion, micro-interaction, systematic polish at 60fps.',
      'Mentor designers and run critique.',
    ],
    skills: ['Product design leadership', 'AI/ML UX patterns', 'Design systems', 'Prototyping (code-adjacent a plus)', 'Research synthesis', 'Accessibility', 'Motion design literacy'],
    eligibility: [
      '5-10 years in product design with shipped AI-adjacent work.',
      'Portfolio demonstrating complex-system design, not just marketing sites.',
    ],
  },
  {
    slug: 'motion-designer-illustration-visual-storytelling',
    departmentId: 'design',
    title: 'Motion Designer (Illustration & Visual Storytelling)',
    level: 'Mid',
    function: 'Give the ecosystem its moving image: product motion, illustrated stories, launch films.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 8,00,000 - 16,00,000 per annum',
    about: 'From an animated hero that explains a venture in eight seconds to course illustrations that make abstract ideas graspable — you will own motion and illustration across products and marketing, in a distinctive house style rather than stock-asset soup.',
    responsibilities: [
      'Create product motion: micro-interactions, animated heroes, onboarding sequences.',
      'Illustrate for education: diagrams, characters, visual metaphors that teach.',
      'Produce launch and explainer videos end to end.',
      'Build a reusable motion language (timing, easing, principles) with the design system.',
      'Optimise everything for web performance: SVG/Lottie-first, 60fps, small payloads.',
    ],
    skills: ['Motion design (After Effects or equivalent)', 'Illustration', 'SVG animation / Lottie', 'Storyboarding', 'Video editing', 'Design-system thinking', 'Web performance awareness'],
    eligibility: [
      '2-6 years in motion/illustration with a strong reel.',
      'Comfort working to product constraints, not just brand briefs.',
    ],
  },

  // ─── PRODUCT & PROGRAMS ───────────────────────────────────────────
  {
    slug: 'program-manager',
    departmentId: 'product-programs',
    title: 'Program Manager',
    level: 'Mid',
    function: 'Make multi-team programmes land: plans that are real, risks surfaced early, delivery honest.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 12,00,000 - 24,00,000 per annum',
    about: 'Many ventures, one small company: the scarcest resource is coordinated attention. You will run programmes that cut across engineering, design, and operations — keeping plans truthful, dependencies visible, and decisions documented, without drowning anyone in process.',
    responsibilities: [
      'Own programme plans: scope, sequencing, dependencies, and honest status.',
      'Run rituals that earn their time; delete the ones that do not.',
      'Surface risks early and drive them to owners and decisions.',
      'Keep written decision records so context survives.',
      'Coordinate launches across product, support, and communications.',
    ],
    skills: ['Program/project management', 'Written communication', 'Risk management', 'Stakeholder management', 'Basic technical literacy', 'Tooling pragmatism'],
    eligibility: [
      '3-8 years managing cross-functional software programmes.',
      'Evidence of shipped programmes, with your specific contribution clear.',
    ],
  },
  {
    slug: 'chief-of-staff',
    departmentId: 'product-programs',
    title: 'Chief of Staff',
    level: 'Lead',
    function: "Multiply the founder's effectiveness: run the operating cadence, own special projects end to end.",
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 25,00,000 - 45,00,000 per annum',
    isFeatured: true,
    about: 'An independent, self-funded company running many ventures needs an operating brain next to the founder: someone who turns intent into cadence, ambiguity into owned workstreams, and meetings into decisions. High trust, high variance, high growth.',
    responsibilities: [
      'Run the company operating rhythm: goals, reviews, decision logs.',
      'Own special projects that have no natural owner — from first draft to done.',
      'Prepare decisions: gather evidence, frame options, force clarity.',
      'Act as connective tissue across ventures; spot collisions early.',
      'Handle sensitive matters with discretion and judgement.',
    ],
    skills: ['Structured thinking', 'Exceptional writing', 'Analytics (SQL/spreadsheets)', 'Project execution', 'Discretion', 'Breadth across product/finance/people'],
    eligibility: [
      '5-10 years in high-performance environments (startups, consulting, operations).',
      'Track record of owning ambiguous problems to completion.',
    ],
  },
  {
    slug: 'innovation-emerging-technologies-manager',
    departmentId: 'product-programs',
    title: 'Innovation & Emerging Technologies Manager',
    level: 'Lead',
    function: 'Scout, evaluate, and pilot emerging technologies; turn signal into staged bets.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 18,00,000 - 35,00,000 per annum',
    about: 'Our thesis spans AI, XR, quantum-era computing, and aerospace. Somebody must separate what is real from what is press release — and turn the real parts into small, honest pilots with kill criteria. You will run the innovation pipeline from horizon scanning to piloted proof.',
    responsibilities: [
      'Run structured horizon scanning across AI, XR, quantum, robotics, and adjacent fields.',
      'Evaluate technologies with evidence: feasibility, cost curves, ecosystem maturity.',
      'Design and run time-boxed pilots with explicit success/kill criteria.',
      'Build university and research-lab relationships for early access to capability.',
      'Publish internal briefs that keep leadership honestly informed.',
    ],
    skills: ['Technology assessment', 'Rapid prototyping literacy', 'Research synthesis', 'Pilot design', 'Technical writing', 'Partnership development'],
    eligibility: [
      '6-12 years across engineering, research, or innovation roles.',
      'Demonstrated judgement: bets you made, bets you killed, and why.',
    ],
  },

  // ─── GROWTH & PARTNERSHIPS ────────────────────────────────────────
  {
    slug: 'business-development-director-global',
    departmentId: 'growth',
    title: 'Business Development Director (Global Strategic Partnerships & Government Relations)',
    level: 'Lead',
    function: 'Open institutional doors: global partnerships, government engagement, large accounts.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 30,00,000 - 55,00,000 per annum',
    isFeatured: true,
    about: 'Our products sell to institutions: universities, education departments, sports federations, enterprises. You will build the partnership engine — including government relationships across education, skilling, and sports — with the patience institutional sales demand and the integrity our brand requires.',
    responsibilities: [
      'Own the institutional partnership strategy and pipeline globally, with India depth.',
      'Build government relationships across education, skilling, and sports ecosystems.',
      'Negotiate and close large, multi-stakeholder agreements.',
      'Represent the company at institutional forums with substance, not fluff.',
      'Build the BD playbook and grow the team as revenue justifies.',
    ],
    skills: ['Institutional/enterprise sales', 'Government engagement', 'Negotiation', 'Pipeline discipline', 'Public speaking', 'Contract literacy'],
    eligibility: [
      '8-15 years in business development with institutional or public-sector wins.',
      'Network in education, sports, or government ecosystems strongly preferred.',
    ],
  },
  {
    slug: 'business-development-manager-institutional',
    departmentId: 'growth',
    title: 'Business Development Manager (Strategic Partnerships & Institutional Growth)',
    level: 'Mid',
    function: 'Build and close the institutional pipeline: universities, schools, academies, enterprises.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 12,00,000 - 25,00,000 per annum',
    about: 'You will take our education and assessment products into institutions: prospecting, demos, pilots, and closed agreements. This is consultative selling of substance to serious buyers — with honest claims and long relationships, not quota-chasing spam.',
    responsibilities: [
      'Own a pipeline of universities, schools, academies, and enterprise accounts.',
      'Run discovery, tailored demos, and pilot programmes.',
      'Negotiate agreements and hand off cleanly to customer success.',
      'Feed structured market signal back to product teams.',
      'Keep CRM discipline: truth in every stage.',
    ],
    skills: ['B2B/institutional sales', 'Consultative selling', 'Demo craft', 'CRM discipline', 'Written proposals', 'EdTech familiarity a plus'],
    eligibility: [
      '3-8 years in B2B sales or partnerships, education sector preferred.',
      'Evidence of deals you sourced and closed yourself.',
    ],
  },
  {
    slug: 'growth-marketing-manager-organic-community',
    departmentId: 'growth',
    title: 'Growth Marketing Manager (Organic Growth & Community)',
    level: 'Mid',
    function: 'Grow without paid crutches: SEO, content, community, and product-led loops.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 12,00,000 - 24,00,000 per annum',
    about: 'We grow on substance: search, content that teaches, community that stays, and product loops that compound. You will own organic growth across the ecosystem — with honest metrics and zero dark patterns, because growth that tricks people is churn with extra steps.',
    responsibilities: [
      'Own organic acquisition: SEO strategy, content calendar, distribution.',
      'Build and nurture learner and developer communities.',
      'Design product-led growth loops (referrals, shareable artefacts) that respect users.',
      'Run honest analytics: cohorts, retention, attribution with caveats.',
      'Coordinate launches with content, community, and PR motions.',
    ],
    skills: ['SEO', 'Content strategy', 'Community building', 'Analytics', 'Copywriting', 'Marketing automation', 'Product-led growth patterns'],
    eligibility: [
      '3-8 years in growth/marketing with organic-first wins you can show.',
    ],
  },
  {
    slug: 'field-sales-executive-enterprise-software',
    departmentId: 'growth',
    title: 'Field Sales Executive (Enterprise Software Solutions)',
    level: 'Mid',
    function: 'Carry our enterprise products into the field: visits, demos, closed deals.',
    engagementType: 'Full-Time',
    location: 'Field (India) with travel',
    duration: PERM,
    salary: 'INR 8,00,000 - 16,00,000 per annum + performance incentives',
    about: 'Institutions in India still buy face to face. You will be on the ground with universities, academies, coaching institutes, and enterprises — demonstrating our platforms, understanding real constraints, and closing business with integrity.',
    responsibilities: [
      'Own a territory: prospect, visit, demo, negotiate, close.',
      'Run on-site product demonstrations and pilot onboarding.',
      'Maintain rigorous CRM hygiene from the field.',
      'Relay ground-truth market intelligence to product and pricing.',
      'Represent the brand: no overselling, no false promises.',
    ],
    skills: ['Field sales', 'Demo delivery', 'Negotiation', 'Territory planning', 'CRM discipline', 'Local-language fluency a plus'],
    eligibility: [
      '2-7 years in field/enterprise sales, software or education preferred.',
      'Willingness to travel extensively within territory.',
    ],
  },
  {
    slug: 'developer-relations-technical-community-manager',
    departmentId: 'growth',
    title: 'Developer Relations & Technical Community Manager',
    level: 'Mid',
    function: 'Make builders successful on our platforms: docs, samples, community, feedback loops.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 12,00,000 - 24,00,000 per annum',
    about: 'Our proctoring SDK, APIs, and tools succeed when outside developers succeed. You will own that relationship: documentation that answers real questions, samples that run first try, a community that helps itself, and a feedback loop engineers actually hear.',
    responsibilities: [
      'Own developer documentation, quickstarts, and sample apps.',
      'Build and moderate the technical community; answer with code, not marketing.',
      'Create technical content: posts, talks, videos, integration guides.',
      'Run the developer feedback loop into product and engineering.',
      'Track honest DevRel metrics: time-to-first-success, doc coverage, community health.',
    ],
    skills: ['Technical writing', 'JavaScript/TypeScript', 'API literacy', 'Community management', 'Public speaking', 'Content production'],
    eligibility: [
      '3-8 years across engineering, DevRel, or technical community roles.',
      'You can code well enough to write the samples yourself.',
    ],
  },

  // ─── PEOPLE & TALENT ──────────────────────────────────────────────
  {
    slug: 'talent-acquisition-manager-strategic-hiring',
    departmentId: 'people',
    title: 'Talent Acquisition Manager (Strategic Hiring)',
    level: 'Mid',
    function: 'Build the hiring engine: sourcing, structured evaluation, candidate experience.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 10,00,000 - 20,00,000 per annum',
    about: 'We hire across frontier engineering, design, sales, and martial arts — often for roles most recruiters have never filled. You will own talent acquisition end to end on our own careers platform: sourcing with craft, evaluating with structure, and treating every candidate the way we would want to be treated.',
    responsibilities: [
      'Own full-cycle recruiting across technical and non-technical roles.',
      'Build sourcing channels beyond job boards: communities, campuses, referrals.',
      'Run structured, bias-aware evaluation with hiring managers.',
      'Own candidate experience: clear timelines, real feedback, honest closure.',
      'Operate and improve our in-house applicant tracking and careers portal.',
    ],
    skills: ['Full-cycle recruiting', 'Technical-role literacy', 'Structured interviewing', 'Sourcing craft', 'Employer branding', 'ATS operations'],
    eligibility: [
      '4-8 years in talent acquisition, startup environments preferred.',
      'Evidence of hard searches you personally closed.',
    ],
  },

  // ─── FINANCE, LEGAL & COMPLIANCE ─────────────────────────────────
  {
    slug: 'finance-corporate-compliance-manager',
    departmentId: 'finance-legal',
    title: 'Finance & Corporate Compliance Manager',
    level: 'Mid',
    function: 'Keep the books true and the company compliant: accounting, filings, controls, payroll.',
    engagementType: 'Full-Time',
    location: 'Dum Dum, Kolkata, West Bengal (on-site)',
    duration: PERM,
    salary: 'INR 10,00,000 - 22,00,000 per annum',
    about: 'A self-funded company survives on financial truth. You will own day-to-day finance and corporate compliance: clean books, on-time filings, payroll people can rely on, and controls that make audits boring — across a group with education, sports, and consumer ventures.',
    responsibilities: [
      'Own bookkeeping, monthly closes, and management reporting.',
      'Ensure statutory compliance: GST, TDS, ROC filings, labour registrations.',
      'Run payroll and vendor payments accurately and on time.',
      'Build internal controls and documentation; prepare for audits.',
      'Support budgeting and cash-flow planning for a bootstrapped group.',
    ],
    skills: ['Accounting (Indian GAAP)', 'GST & direct tax compliance', 'Company law basics', 'Payroll operations', 'Accounting software', 'Spreadsheets to an advanced level'],
    eligibility: [
      'CA/CMA (or inter) or M.Com with 4-8 years of hands-on experience.',
      'Experience across compliance for private limited companies.',
      'Based in or willing to relocate to Kolkata.',
    ],
  },
  {
    slug: 'legal-intellectual-property-manager',
    departmentId: 'finance-legal',
    title: 'Legal & Intellectual Property Manager',
    level: 'Mid',
    function: 'Protect what we build: contracts, IP strategy, privacy, and platform policies.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 12,00,000 - 25,00,000 per annum',
    about: 'We generate IP constantly — software, brands, research, content — and we operate platforms with real legal surface: education records, identity verification, payments, a dating venture. You will own legal end to end: pragmatic contracts, deliberate IP protection, and privacy compliance treated as a feature.',
    responsibilities: [
      'Draft and negotiate commercial contracts: institutional sales, vendors, partnerships.',
      'Own IP strategy: trademarks, copyrights, patent evaluation, trade-secret hygiene.',
      'Run privacy compliance (DPDP Act, GDPR-readiness) and data-protection documentation.',
      'Write and maintain platform terms and policies in language humans understand.',
      'Manage disputes and external counsel efficiently.',
    ],
    skills: ['Contract drafting & negotiation', 'IP law (trademark/copyright)', 'Privacy law (DPDP/GDPR)', 'Tech-platform legal issues', 'Clear drafting', 'Risk judgement'],
    eligibility: [
      'LL.B. with 4-8 years in tech/IP practice (firm or in-house).',
      'Experience with software and platform businesses strongly preferred.',
    ],
  },

  // ─── OPERATIONS & SUPPORT ─────────────────────────────────────────
  {
    slug: 'customer-success-product-support-associate',
    departmentId: 'operations',
    title: 'Customer Success & Product Support Associate',
    level: 'Junior',
    function: 'Be the human in the loop: resolve issues, onboard users, feed product truth back.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 4,00,000 - 9,00,000 per annum',
    about: 'Learners mid-exam, institutions mid-rollout, applicants mid-payment: when they need help, speed and honesty matter. You will own front-line support and onboarding across products — and act as the most reliable source of ground truth our product teams have.',
    responsibilities: [
      'Resolve support requests across channels within honest SLAs.',
      'Onboard new institutional users; run training sessions.',
      'Escalate with precision: reproduction steps, impact, urgency.',
      'Turn recurring issues into documentation and product tickets.',
      'Track satisfaction honestly and report it unvarnished.',
    ],
    skills: ['Written & spoken communication', 'Troubleshooting method', 'Empathy under pressure', 'Documentation', 'Basic SQL/log reading a plus', 'Hindi + English; more languages welcome'],
    eligibility: [
      '0-4 years in support/success roles; graduates welcome.',
      'Calm, precise communication — we will test for it.',
    ],
  },
  {
    slug: 'technical-writer-knowledge-management-specialist',
    departmentId: 'operations',
    title: 'Technical Writer & Knowledge Management Specialist',
    level: 'Mid',
    function: 'Make knowledge usable: docs, guides, and an internal knowledge base that stays true.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 8,00,000 - 18,00,000 per annum',
    about: 'A many-product company drowns without written truth. You will own documentation across the ecosystem — user guides, admin manuals, API references, internal runbooks — and the knowledge system that keeps it current instead of quietly rotting.',
    responsibilities: [
      'Write and maintain user, admin, and developer documentation.',
      'Build the internal knowledge base: structure, ownership, review cycles.',
      'Turn support patterns into self-serve articles.',
      'Establish style, templates, and docs-as-code workflows.',
      'Audit for rot: outdated pages get fixed or deleted, not ignored.',
    ],
    skills: ['Technical writing', 'Information architecture', 'Docs-as-code (Markdown/Git)', 'API documentation', 'Editing discipline', 'Screenshot/diagram craft'],
    eligibility: [
      '2-6 years writing documentation for software products.',
      'Samples required: real docs you wrote, before/after preferred.',
    ],
  },

  // ─── MARTIAL ARTS & SPORTS ────────────────────────────────────────
  {
    slug: 'executive-director-global-martial-arts-development',
    departmentId: 'martial-arts',
    title: 'Executive Director - Global Martial Arts Development',
    level: 'Lead',
    function: 'Build the global martial-arts platform: federations, academies, programmes, standards.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 25,00,000 - 50,00,000 per annum',
    isFeatured: true,
    productMatch: 'karate',
    about: 'Our martial-arts platform serves the global karate community: instructor discovery, dojo management, certification tracking, tournament infrastructure. You will lead its worldwide development — building relationships with federations and academies, setting programme standards, and growing the platform from strong foundation to global default.',
    responsibilities: [
      'Own global strategy and growth for the martial-arts platform.',
      'Build relationships with federations, associations, and elite academies.',
      'Define certification and instructor-quality standards with credible partners.',
      'Launch country programmes; recruit regional leadership.',
      'Represent the platform at international sporting forums.',
    ],
    skills: ['Sports administration', 'Federation/government relations', 'Programme building', 'Partnership negotiation', 'Public representation', 'Martial-arts domain credibility'],
    eligibility: [
      '10+ years across sports administration, federation leadership, or elite coaching.',
      'Deep martial-arts credibility (practitioner or administrator).',
      'International network strongly preferred.',
    ],
  },
  {
    slug: 'karate-instructor-martial-arts-expert',
    departmentId: 'martial-arts',
    title: 'Karate Instructor & Martial Arts Expert',
    level: 'Mid',
    function: 'Teach with excellence; shape the curriculum and content of the platform.',
    engagementType: 'Full-Time',
    location: 'India (hybrid: in-person instruction + online content)',
    duration: PERM,
    salary: 'INR 4,00,000 - 10,00,000 per annum',
    productMatch: 'karate',
    about: 'We are building the definitive platform for karate instruction — and it must be shaped by people who actually teach. You will instruct students, co-design curriculum and grading content, and appear in the instructional material that reaches practitioners worldwide.',
    responsibilities: [
      'Deliver structured karate instruction across age groups and levels.',
      'Co-design curriculum, syllabi, and grading standards for the platform.',
      'Record and review instructional content (kata, kumite, fundamentals).',
      'Uphold safety-first, advisory-only assessment practices.',
      'Mentor junior instructors joining the platform.',
    ],
    skills: ['Karate instruction (black belt, recognised lineage)', 'Curriculum design', 'On-camera teaching', 'Student safety practice', 'Hindi + English instruction'],
    eligibility: [
      'Black belt (1st Dan or above) with verifiable lineage/federation standing.',
      '4+ years teaching experience across levels.',
      'Comfortable teaching on camera.',
    ],
  },

  // ─── INNOVATION & GRANTS ──────────────────────────────────────────
  {
    slug: 'grants-innovation-funding-lead',
    departmentId: 'innovation-grants',
    title: 'Grants & Innovation Funding Lead (Government Programmes)',
    level: 'Lead',
    function: 'Win non-dilutive funding: government grants, innovation schemes, R&D incentives.',
    engagementType: 'Full-Time',
    location: REMOTE_IN,
    duration: PERM,
    salary: 'INR 15,00,000 - 30,00,000 per annum',
    isFeatured: true,
    about: 'EduRankAI deliberately takes no external equity funding — independence keeps our decisions unbiased and our judgement clear. That makes non-dilutive capital strategic: government research grants, startup and innovation schemes, R&D tax incentives, education and skilling missions, and space/defence innovation challenges. You will own this entire function: knowing every programme we qualify for, writing applications that win, and managing compliance so the money keeps flowing.',
    responsibilities: [
      'Map and track every relevant funding programme: national and state startup missions, R&D grants, education/skilling schemes, innovation challenges, and incubation benefits.',
      'Own the grant pipeline end to end: eligibility analysis, application writing, budgets, submission, follow-through.',
      'Write technically credible proposals with founders and engineers — substance, not padding.',
      'Manage post-award compliance: utilisation certificates, milestone reporting, audits.',
      'Build relationships with programme officers, incubators, and government innovation bodies.',
      'Advise leadership on structuring projects to be fundable without distorting the mission.',
    ],
    skills: ['Grant writing (government programmes)', 'Indian innovation-funding landscape', 'Budget preparation', 'Compliance & reporting', 'Technical writing', 'Government liaison', 'Programme management'],
    eligibility: [
      '6-12 years in grants, innovation funding, incubation, or public-programme management.',
      'Grants you personally won — names and amounts, verifiable.',
      'Understanding of deep-tech domains (AI, XR, aerospace) strong enough to write about them honestly.',
    ],
  },

  // ─── INTERNSHIPS ──────────────────────────────────────────────────
  {
    slug: 'aerospace-research-engineering-intern',
    departmentId: 'ai-research',
    title: 'Aerospace Research & Engineering Intern',
    level: 'Intern',
    function: 'Contribute to frontier aerospace research: simulation, CFD, systems analysis.',
    engagementType: 'Internship',
    location: REMOTE_IN,
    duration: '6 months',
    salary: 'Stipend: INR 15,000 - 35,000 per month',
    about: 'Our aerospace research programme explores autonomous swarm concepts across scales. As an intern you will do real research work — simulation, parametric analysis, documentation of engineering trades — alongside the team, with your contributions credited.',
    responsibilities: [
      'Run and document simulations (flight profiles, CFD-adjacent analysis).',
      'Build parametric models and engineering trade studies.',
      'Contribute to research documentation and internal papers.',
      'Present findings in research reviews.',
    ],
    skills: ['Python or MATLAB', 'Aerospace/mechanical fundamentals', 'Simulation literacy', 'Technical writing', 'Curiosity with rigour'],
    eligibility: [
      'Pursuing or recently completed B.Tech/M.Tech in Aerospace, Mechanical, or allied fields.',
      'Coursework or projects in flight mechanics, CFD, or control systems.',
    ],
  },
  {
    slug: 'ui-ux-design-intern',
    departmentId: 'design',
    title: 'UI/UX Design Intern',
    level: 'Intern',
    function: 'Design real screens for real products, with mentorship and a portfolio to show for it.',
    engagementType: 'Internship',
    location: REMOTE_IN,
    duration: '3-6 months',
    salary: 'Stipend: INR 10,000 - 20,000 per month',
    about: 'You will design production screens across our ecosystem — not fake briefs. Expect real constraints (accessibility, performance, existing design system), real critique, and shipped work you can point to.',
    responsibilities: [
      'Design flows and screens under mentorship of senior designers.',
      'Contribute components to the design system.',
      'Join user-testing sessions; synthesise findings.',
      'Iterate from critique quickly and without ego.',
    ],
    skills: ['Figma or equivalent', 'Visual fundamentals (type, spacing, colour)', 'Curiosity about accessibility', 'Receptiveness to critique'],
    eligibility: [
      'Design student or early-career designer with a portfolio (student work fine).',
      'Available at least 20 hours/week.',
    ],
  },
  {
    slug: 'campus-ambassador',
    departmentId: 'growth',
    title: 'Campus Ambassador',
    level: 'Intern',
    function: 'Represent EduRankAI on your campus: events, community, honest advocacy.',
    engagementType: 'Internship',
    location: 'Your campus (India)',
    duration: '6 months (renewable)',
    salary: 'Performance-based rewards + certificate + fee-waiver benefits',
    about: 'Bring EduRankAI to your campus: run events, help peers use our free tools (resume builder, courses, assessments), and channel student feedback straight to the team. Top ambassadors earn rewards, recommendation letters, and priority consideration for internships.',
    responsibilities: [
      'Organise campus events, workshops, and challenges.',
      'Introduce peers to the platform honestly — no spam, no false claims.',
      'Gather structured student feedback for product teams.',
      'Coordinate with the growth team on campaigns.',
    ],
    skills: ['Communication', 'Event organisation', 'Social media basics', 'Initiative'],
    eligibility: [
      'Currently enrolled college student in India.',
      'Active standing in campus communities preferred.',
    ],
  },
];
