/* ICIRE — in-house AI Career Coach (NO external LLM). The "conversation" is owned
 * intent classification (pattern matching over the message) + template answers
 * filled with REAL data from the career engine. Nothing is generated by an LLM and
 * nothing is fabricated — every answer is composed from the applicant's own graph,
 * real job listings, and the engine's honest computations. */
import { classifyLearned } from "./intentClassifier"

export type Intent =
  | "help" | "learn" | "level" | "matches" | "resume" | "interview"
  | "dna" | "path" | "progress" | "salary" | "fallback"

// Ordered rules — first match wins. Order chosen to avoid collisions (e.g. a
// résumé question that also says "improve" must resolve to résumé, not "learn").
// No trailing \b so plurals ("jobs", "skills") still match; input is
// accent-stripped first so "résumé" == "resume".
// Specific-intent rules first; the greeting/help rule is LAST so a message like
// "help me improve my résumé" routes to résumé, not the generic menu. Genuine
// greetings ("hi", "menu", bare "help") match no specific rule and fall through.
const RULES: [RegExp, Intent][] = [
  [/(\bresume|\bcv\b|\bats\b|cover letter|bullet)/i, "resume"],
  [/\b(interview|mock|whiteboard|behavioural|behavioral|prep)/i, "interview"],
  [/\b(salary|salaries|pay|paid|compensation|ctc|stipend|package|earn|how much)/i, "salary"],
  [/\b(best[\w -]*(job|role|fit|match)|which (job|role)|jobs? for me|roles? for me|suit|recommend|good fit|what should i apply)/i, "matches"],
  [/\b(career path|where (can|could|do) i go|progression|promotion|next role|grow into|move up|future role|ladder)/i, "path"],
  [/\b(learn|study|upskill|skill ?up|what.*(next|learn)|which skill|skill gap|close .*gap|improve my skills|highest.?leverage|pick up)/i, "learn"],
  [/\b(senior|junior|mid.?level|seniority|my level|am i ready|ready for|experienced enough|principal|staff)/i, "level"],
  [/\b(strength|weak|good at|career dna|\bdna\b|archetype|fingerprint|who am i|my profile|describe me)/i, "dna"],
  [/\b(progress|improv|momentum|over time|trend|growth|getting better)/i, "progress"],
  // Generic "show me jobs" — placed AFTER the specific intents so it only catches
  // bare role/opening queries ("any job", "show openings") that would otherwise fall
  // through to nothing. This is what lets "any job with more than 50%" resolve.
  [/\b(jobs?|roles?|positions?|openings?|vacanc\w*|opportunit\w*|hiring|apply|application|match(es)?|fit)\b/i, "matches"],
  [/\b(hi|hello|hey|help|what can you|who are you|how (do|does) (you|this) work|options|menu|start)\b/i, "help"],
]

const normI = (t: string) => (t || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")

export type Slots = { threshold?: number; remote?: boolean; type?: string }

/** Pull structured filters out of a query, in-house. Understands match thresholds
 * ("more than 50%", "at least 60", "70%+", ">= 40"), remote, and internship. */
export function extractSlots(text: string): Slots {
  const t = normI(text)
  const slots: Slots = {}
  // A number immediately followed by a time/count unit is NOT a match percentage
  // ("5+ years", "over 3 months", "1000 openings") — mask those spans first so they
  // never populate the threshold.
  const masked = t.replace(/\d+\s*(?:\+\s*)?(?:years?|yrs?|months?|mos?|weeks?|days?|hrs?|hours?|openings?|roles?|jobs?|positions?|applicants?|vacanc\w*)\b/g, " ")
  // \d+ (not \d{1,3}) so an out-of-range value reaches the 0..100 guard and is
  // rejected, instead of being truncated to a spurious in-range number.
  const m =
    masked.match(/(?:more than|greater than|higher than|over|above|at least|\bminimum\b|\bmin\b|atleast|>=?)\s*(\d+)\s*(?:%|percent|pct)?/) ||
    masked.match(/(\d+)\s*(?:%|percent|pct)\s*\+?/) ||
    masked.match(/(\d+)\s*(?:%|percent|pct)?\s*(?:or more|or above|or higher|and above|and up)/)
  if (m) { const n = parseInt(m[1], 10); if (n >= 0 && n <= 100) slots.threshold = n }
  if (/\bremote\b|work from home|\bwfh\b|from home/.test(t)) slots.remote = true
  if (/\bintern(ship)?s?\b/.test(t)) slots.type = "internship"
  return slots
}

export function classifyIntent(text: string, slots?: Slots): Intent {
  // Lowercase + strip accents so "résumé" -> "resume", etc.
  const t = normI(text)
  // Explicit intent rules win FIRST — so "am I ready for senior with 5+ years?"
  // routes to level, not matches, even when a number is present.
  for (const [re, intent] of RULES) if (re.test(t)) return intent
  // Only a BARE match-percentage with no explicit intent ("50%+", "over 60") falls
  // through to matches. (The generic RULES 'jobs' rule already caught job-worded ones.)
  if (slots?.threshold != null) return "matches"
  // Learned fallback: the in-house Naive Bayes classifier (trained on intentData)
  // handles paraphrases the rules don't. Only trust a confident, clear prediction;
  // otherwise show the help menu rather than guess.
  const learned = classifyLearned(text)
  return learned.confident ? learned.intent : "help"
}

export type ParsedQuery = { intent: Intent; slots: Slots }
/** One call: structured filters + intent. Used by the coach route. */
export function parseQuery(text: string): ParsedQuery {
  const slots = extractSlots(text)
  return { intent: classifyIntent(text, slots), slots }
}

// Starter prompts shown in the chat.
export const STARTERS = [
  "What should I learn next?",
  "What are my best-fit jobs?",
  "Am I ready for senior roles?",
  "How do I improve my résumé?",
  "How do I prepare for an interview?",
  "What's my Career DNA?",
]

// Follow-up suggestions offered after an answer (kept relevant to the intent).
export const FOLLOWUPS: Record<Intent, string[]> = {
  help: STARTERS.slice(0, 4),
  learn: ["What are my best-fit jobs?", "What's my career path?", "How do I improve my résumé?"],
  level: ["What's my career path?", "What should I learn next?", "What are my strengths?"],
  matches: ["How do I improve my résumé?", "How do I prepare for an interview?", "What should I learn next?"],
  resume: ["How do I prepare for an interview?", "What are my best-fit jobs?", "What should I learn next?"],
  interview: ["How do I improve my résumé?", "Am I ready for senior roles?", "What are my best-fit jobs?"],
  dna: ["What's my career path?", "Am I ready for senior roles?", "What should I learn next?"],
  path: ["What should I learn next?", "Am I ready for senior roles?", "What are my best-fit jobs?"],
  progress: ["What should I learn next?", "What's my Career DNA?", "What are my best-fit jobs?"],
  salary: ["What's my career path?", "What are my best-fit jobs?", "What should I learn next?"],
  fallback: STARTERS.slice(0, 4),
}

export function list(a: string[]): string {
  const x = a.filter(Boolean)
  if (x.length <= 1) return x[0] || ""
  return x.slice(0, -1).join(", ") + " and " + x[x.length - 1]
}
