/* ICIRE — in-house AI Career Coach (NO external LLM). The "conversation" is owned
 * intent classification (pattern matching over the message) + template answers
 * filled with REAL data from the career engine. Nothing is generated by an LLM and
 * nothing is fabricated — every answer is composed from the applicant's own graph,
 * real job listings, and the engine's honest computations. */

export type Intent =
  | "help" | "learn" | "level" | "matches" | "resume" | "interview"
  | "dna" | "path" | "progress" | "salary" | "fallback"

// Ordered rules — first match wins. Order chosen to avoid collisions (e.g. a
// résumé question that also says "improve" must resolve to résumé, not "learn").
// No trailing \b so plurals ("jobs", "skills") still match; input is
// accent-stripped first so "résumé" == "resume".
// Specific-intent rules first; the greeting/help rule is LAST so a message like
// "help me improve my résumé" routes to résumé, not the generic menu. Genuine
// greetings ("hi", "menu", bare "help") match no specific rule and fall through.
const RULES: [RegExp, Intent][] = [
  [/(\bresume|\bcv\b|\bats\b|cover letter|bullet)/i, "resume"],
  [/\b(interview|mock|whiteboard|behavioural|behavioral|prep)/i, "interview"],
  [/\b(salary|salaries|pay|paid|compensation|ctc|stipend|package|earn|how much)/i, "salary"],
  [/\b(best[\w -]*(job|role|fit|match)|which (job|role)|jobs? for me|roles? for me|suit|recommend|good fit|what should i apply)/i, "matches"],
  [/\b(career path|where (can|could|do) i go|progression|promotion|next role|grow into|move up|future role|ladder)/i, "path"],
  [/\b(learn|study|upskill|skill ?up|what.*(next|learn)|which skill|skill gap|close .*gap|improve my skills|highest.?leverage|pick up)/i, "learn"],
  [/\b(senior|junior|mid.?level|seniority|my level|am i ready|ready for|experienced enough|principal|staff)/i, "level"],
  [/\b(strength|weak|good at|career dna|\bdna\b|archetype|fingerprint|who am i|my profile|describe me)/i, "dna"],
  [/\b(progress|improv|momentum|over time|trend|growth|getting better)/i, "progress"],
  // Generic "show me jobs" — placed AFTER the specific intents so it only catches
  // bare role/opening queries ("any job", "show openings") that would otherwise fall
  // through to nothing. This is what lets "any job with more than 50%" resolve.
  [/\b(jobs?|roles?|positions?|openings?|vacanc\w*|opportunit\w*|hiring|apply|application|match(es)?|fit)\b/i, "matches"],
  [/\b(hi|hello|hey|help|what can you|who are you|how (do|does) (you|this) work|options|menu|start)\b/i, "help"],
]

// Token bags for a last-resort scored fallback — when no rule fires, route to the
// intent whose vocabulary the message overlaps most (still fully deterministic,
// no LLM). Keeps paraphrases ("point me somewhere I'd do well") on the rails.
const BAGS: Record<Exclude<Intent, "fallback" | "help">, string[]> = {
  matches: ["job", "jobs", "role", "roles", "match", "fit", "apply", "opening", "position", "opportunity", "hire", "hiring", "suited", "good"],
  learn: ["learn", "skill", "skills", "study", "course", "improve", "upskill", "gap", "next", "grow"],
  level: ["senior", "junior", "level", "ready", "seniority", "experienced", "enough", "promotion"],
  resume: ["resume", "cv", "ats", "bullet", "cover", "letter", "keyword"],
  interview: ["interview", "mock", "prep", "question", "questions", "rehearse", "round"],
  dna: ["strength", "strengths", "weakness", "dna", "archetype", "profile", "describe", "who"],
  path: ["path", "progression", "future", "ladder", "trajectory", "direction", "become", "move"],
  progress: ["progress", "momentum", "trend", "over", "time", "better", "growth", "improving"],
  salary: ["salary", "pay", "compensation", "stipend", "earn", "money", "wage", "package"],
}
const normI = (t: string) => (t || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")

export type Slots = { threshold?: number; remote?: boolean; type?: string }

/** Pull structured filters out of a query, in-house. Understands match thresholds
 * ("more than 50%", "at least 60", "70%+", ">= 40"), remote, and internship. */
export function extractSlots(text: string): Slots {
  const t = normI(text)
  const slots: Slots = {}
  const m =
    t.match(/(?:more than|greater than|higher than|over|above|at least|minimum|min|atleast|>=?)\s*(\d{1,3})\s*(?:%|percent|pct)?/) ||
    t.match(/(\d{1,3})\s*(?:%|percent|pct)?\s*\+/) ||
    t.match(/(\d{1,3})\s*(?:%|percent|pct)?\s*(?:or more|or above|or higher|and above|and up)/) ||
    t.match(/(?:above|over)\s*(\d{1,3})/)
  if (m) { const n = parseInt(m[1], 10); if (n >= 0 && n <= 100) slots.threshold = n }
  if (/\bremote\b|work from home|\bwfh\b|from home/.test(t)) slots.remote = true
  if (/\bintern(ship)?s?\b/.test(t)) slots.type = "internship"
  return slots
}

export function classifyIntent(text: string, slots?: Slots): Intent {
  // Lowercase + strip accents so "résumé" -> "resume", etc.
  const t = normI(text)
  // A match-percentage threshold almost always refers to job fit — route it to
  // matches even if phrased without an explicit job word ("show me 50%+").
  if (slots?.threshold != null && !/\b(learn|salary|pay|interview|resume|cv)\b/.test(t)) return "matches"
  for (const [re, intent] of RULES) if (re.test(t)) return intent
  // Scored fallback: pick the intent whose vocabulary overlaps the message most.
  const toks = new Set(t.split(/[^a-z0-9]+/).filter(Boolean))
  let best: Intent = "help", bestScore = 0
  for (const [intent, bag] of Object.entries(BAGS) as [Exclude<Intent, "fallback" | "help">, string[]][]) {
    let s = 0
    for (const w of bag) if (toks.has(w)) s++
    if (s > bestScore) { bestScore = s; best = intent }
  }
  return bestScore >= 1 ? best : "help"
}

export type ParsedQuery = { intent: Intent; slots: Slots }
/** One call: structured filters + intent. Used by the coach route. */
export function parseQuery(text: string): ParsedQuery {
  const slots = extractSlots(text)
  return { intent: classifyIntent(text, slots), slots }
}

// Starter prompts shown in the chat.
export const STARTERS = [
  "What should I learn next?",
  "What are my best-fit jobs?",
  "Am I ready for senior roles?",
  "How do I improve my résumé?",
  "How do I prepare for an interview?",
  "What's my Career DNA?",
]

// Follow-up suggestions offered after an answer (kept relevant to the intent).
export const FOLLOWUPS: Record<Intent, string[]> = {
  help: STARTERS.slice(0, 4),
  learn: ["What are my best-fit jobs?", "What's my career path?", "How do I improve my résumé?"],
  level: ["What's my career path?", "What should I learn next?", "What are my strengths?"],
  matches: ["How do I improve my résumé?", "How do I prepare for an interview?", "What should I learn next?"],
  resume: ["How do I prepare for an interview?", "What are my best-fit jobs?", "What should I learn next?"],
  interview: ["How do I improve my résumé?", "Am I ready for senior roles?", "What are my best-fit jobs?"],
  dna: ["What's my career path?", "Am I ready for senior roles?", "What should I learn next?"],
  path: ["What should I learn next?", "Am I ready for senior roles?", "What are my best-fit jobs?"],
  progress: ["What should I learn next?", "What's my Career DNA?", "What are my best-fit jobs?"],
  salary: ["What's my career path?", "What are my best-fit jobs?", "What should I learn next?"],
  fallback: STARTERS.slice(0, 4),
}

export function list(a: string[]): string {
  const x = a.filter(Boolean)
  if (x.length <= 1) return x[0] || ""
  return x.slice(0, -1).join(", ") + " and " + x[x.length - 1]
}
