/* ICIRE — pure, in-house trainer for the self-trained semantic skill model. Given
 * skill-sets (one per "document" — a job, a candidate profile, a course), it learns
 * skill<->skill relatedness as normalised pointwise mutual information (nPMI) over
 * how skills genuinely co-occur. NO external libs/models/LLM: pure statistics.
 *
 * Deliberately pure + dependency-free so the SAME math backs both the CLI trainer
 * (scripts/train-semantic.mjs) and the runtime retrainer (/api/cron/train-semantic) —
 * identical results either way — and so it is directly unit-testable. */

export type TrainedModel = {
  trained: { docs: number; skills: number; pairs: number; sources?: Record<string, number>; at: string } | null
  pairs: Record<string, number> // "SkillA|SkillB" (A<B) -> nPMI in [0,1]
}

export type TrainOpts = {
  minCo?: number      // a pair must co-occur in >= this many docs
  minNpmi?: number    // keep only genuinely-associated pairs
  maxNeigh?: number   // cap neighbours per skill (strongest kept)
  isSoft?: (s: string) => boolean // drop mixed soft<->technical edges (broad noise)
  at?: string         // timestamp stamped into the model (caller supplies; keeps this pure)
  sources?: Record<string, number> // provenance counts for transparency
}

/** Learn nPMI relatedness from skill-sets. Each inner array is the canonical skills
 * present in one document; order/duplicates don't matter. */
export function computeModel(docs: string[][], opts: TrainOpts = {}): TrainedModel {
  const MIN_CO = opts.minCo ?? 4, MIN_NPMI = opts.minNpmi ?? 0.15, MAX_NEIGH = opts.maxNeigh ?? 14
  const isSoft = opts.isSoft || (() => false)

  const docFreq = new Map<string, number>()
  const pairFreq = new Map<string, number>()
  let n = 0
  for (const raw of docs) {
    const set = Array.from(new Set(raw.filter(Boolean))).sort()
    if (set.length < 2) continue
    n++
    for (const a of set) docFreq.set(a, (docFreq.get(a) || 0) + 1)
    for (let i = 0; i < set.length; i++) for (let k = i + 1; k < set.length; k++) {
      const key = set[i] + "|" + set[k]
      pairFreq.set(key, (pairFreq.get(key) || 0) + 1)
    }
  }

  const scored: { key: string; a: string; b: string; npmi: number }[] = []
  for (const [key, f] of pairFreq) {
    if (f < MIN_CO) continue
    const bar = key.indexOf("|")
    const a = key.slice(0, bar), b = key.slice(bar + 1)
    // Soft skills co-occur with almost everything → mixed soft/technical PMI is
    // broad noise. Keep soft<->soft and tech<->tech, which are signal.
    if (isSoft(a) !== isSoft(b)) continue
    const pab = f / n, pa = (docFreq.get(a) as number) / n, pb = (docFreq.get(b) as number) / n
    const npmi = Math.log(pab / (pa * pb)) / -Math.log(pab) // in [-1, 1]
    if (npmi >= MIN_NPMI) scored.push({ key, a, b, npmi: Math.min(1, npmi) })
  }

  // cap neighbours per skill by strength; keep the union
  const per = new Map<string, typeof scored>()
  for (const s of scored) {
    ;(per.get(s.a) || per.set(s.a, []).get(s.a) as typeof scored).push(s)
    ;(per.get(s.b) || per.set(s.b, []).get(s.b) as typeof scored).push(s)
  }
  const keep = new Set<string>()
  for (const list of per.values()) { list.sort((x, y) => y.npmi - x.npmi); for (const s of list.slice(0, MAX_NEIGH)) keep.add(s.key) }

  const pairs: Record<string, number> = {}
  for (const s of scored) if (keep.has(s.key)) pairs[s.key] = Math.round(s.npmi * 1000) / 1000

  return { trained: { docs: n, skills: docFreq.size, pairs: Object.keys(pairs).length, sources: opts.sources, at: opts.at || "" }, pairs }
}

/** Serialize a trained model to the exact TypeScript that lib/career/semantic-model.ts
 * expects. Kept here so CLI and any other caller emit byte-identical files. */
export function serializeModel(m: TrainedModel): string {
  const pairs = m.pairs
  const sortedKeys = Object.keys(pairs).sort()
  const trained = m.trained
    ? `{ docs: ${m.trained.docs}, skills: ${m.trained.skills}, pairs: ${m.trained.pairs}, sources: ${JSON.stringify(m.trained.sources || {})}, at: ${JSON.stringify(m.trained.at)} }`
    : "null"
  return `/* AUTO-GENERATED by scripts/train-semantic.mjs (or /api/cron/train-semantic) —
 * a self-trained skill relatedness model (normalised PMI) learned from Vrittih's OWN
 * data: live jobs + candidate profiles + courses. No external model, no download, no
 * LLM. Do NOT edit by hand — re-run \`npm run train:semantic\` to refresh. An empty
 * \`pairs\` map is valid: the semantic layer falls back to the curated ontology. */
export type SemanticModel = {
  trained: { docs?: number; jobs?: number; skills: number; pairs: number; sources?: Record<string, number>; at: string } | null
  pairs: Record<string, number>
}

export const MODEL: SemanticModel = {
  trained: ${trained},
  pairs: ${JSON.stringify(pairs, sortedKeys, 2)},
}
`
}
